import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const peydaReg = localFont({
  src: "../../public/fonts/PeydaFaNum-Regular.woff2",

  variable: "--font-peydaReg",
  display: "swap",
});
const peydaMed = localFont({
  src: "../../public/fonts/PeydaFaNum-Medium.woff2",

  variable: "--font-peydaMed",
  display: "swap",
});
const peydaSemi = localFont({
  src: "../../public/fonts/PeydaFaNum-SemiBold.woff2",

  variable: "--font-peydaSemi",
  display: "swap",
});
const peydaBold = localFont({
  src: "../../public/fonts/PeydaFaNum-Bold.woff2",

  variable: "--font-peydaBold",
  display: "swap",
});



// const payda =
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} 

          ${peydaReg.variable}
          ${peydaMed.variable}
          ${peydaSemi.variable}
          ${peydaBold.variable}
          
          } antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
